---

- name: copy easy-rsa files to openvpn dir
  command: cp -r /usr/share/easy-rsa/ /etc/openvpn
  tags:
    - easyrsa

- name: ensure key directory exists
  file:
    path: /etc/openvpn/easy-rsa/keys
    state: directory
    owner: root
    group: root
    mode: 0750
  tags:
    - easyrsa

- name: copy vars file for cert generation
  template:
    src: easy_rsa_vars.j2 
    dest: /etc/openvpn/easy-rsa/vars
  tags:
    - easyrsa

- name: build certificate authority
  shell: source ./vars && ./pkitool --initca
  args:
    chdir: /etc/openvpn/easy-rsa
    executable: /bin/bash
    creates: /etc/openvpn/easy-rsa/ca.crt
  tags:
    - easyrsa

- name: ensure server certificate exists
  action: easyrsa_cert
      state=present
      ca_root=/etc/openvpn/easy-rsa/
      cn={{ssl_key_server_name}}
      key_usage=server
  tags:
    - easyrsa

- name: ensure client certificate exists
  action: easyrsa_cert
    state=present
    ca_root=/etc/openvpn/easy-rsa/
    cn="{{ssl_key_client_name}}"
    key_usage=client
  tags:
    - easyrsa
