---
- name: allow ssh through firewall
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: allow openvpn through firewall
  ufw:
    rule: allow
    port: 1194

- name: ensure ufw is running
  service:
    name: ufw
    state: running
    
