---
- name: create vpn server
  hosts: digitalocean_vpn_client
  roles:
    - { role: create-droplet, tags: vpn }

- name: configure vpn server
  hosts: digitalocean_vpn_server
  vars_files:
    - vars.yml
  roles:
    - { role: configure-server, tags: vpn }

- name: configure vpn client
  vars_files:
    - vars.yml
#  vars_prompt:
#    - name: ansible_sudo_pass
#      prompt: Sudo password
#      private: yes
  hosts: digitalocean_vpn_client
  roles:
    - { role: configure-client, tags: vpn }
  # sudo required for writing NetworkManager connection files,
  # which must be 600 root.
