---
- name: Create VPN server on DigitalOcean.
  hosts: localhost
  vars_files:
    - vars.yml
  roles:
    - role: ~/gits/ansible-roles/create-droplet
      droplet_name: vpn
      droplet_groups: digitalocean_vpn_server
      droplet_private_networking: false
      tags: vpn

- name: Configure VPN server.
  hosts: digitalocean_vpn_server
  # Hardcoding "root" as login user, since it's default
  # on DigitalOcean. If you use a custom box with a
  # different login account, remove this line.
  #  user: root
  vars_files:
    - vars.yml
  sudo: yes
  roles:
    - role: stouts.openvpn
      openvpn_clients:
        - laptop
        - phone
      tags: vpn

- name: Configure VPN client.
  vars_files:
    - vars.yml
#  vars_prompt:
#    - name: ansible_sudo_pass
#      prompt: Sudo password
#      private: yes
  hosts: digitalocean_vpn_client
  roles:
    - role: configure-client
        # Autoconfiguration for VPN client (localhost) via nmcli
        # is disabled by default. nmcli versions change quickly,
        # so will likely need to do version checking, which is a PITA.
        # Better yet, there might be a fine Ansible module around the corner.
      vpn_auto_configure: false
      tags: vpn

  # sudo required for writing NetworkManager connection
  # files in /etc/NetworkManager, and setting them to 600.
  # The config files must be root-owned 600, otherwise
  # NM won't trust them. Rather than prompt folks for a sudo
  # password, I'd like to find a way to leverage dbus or nmcli
  # to create the connection without superuser permissions.
