---
- name: configure vpn client
  hosts: digitalocean_vpn_client
  roles:
    - { role: digitalocean-vpn/client, tags: vpn }

- name: configure vpn server
  hosts: digitalocean_vpn_server
  roles:
    - { role: digitalocean-vpn/server, tags: vpn}
    - { role: zufallsheld.ssh-hardening, tags: ssh-hardening }
