---
- hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - defaults/main.yml
  
  tasks:
  - easy_install: name=dopy
  - digital_ocean:
      command: droplet
      state: present
      name: vpn
      unique_name: true

      size_id: "{{ size_id }}"
      region_id: "{{ region_id }}"
      image_id: "{{ image_id }}"

      client_id: "{{ do_client_id }}"
      api_key: "{{ do_api_key }}"
      ssh_key_ids: "{{ do_ssh_key_id }}"

      wait_timeout: 200

    register: vpn_droplet
    tags:
      - digital_ocean
      - provision


