---
- name: update apt cache
  apt: update_cache=yes cache_valid_time=86400

- name: install required packages
  apt: pkg={{ item }} state=latest
  with_items:
  - git
  - python-keyczar # required to use accelerated mode
