---
- name: create openvpn config
  template:
    src: templates/server.conf.j2
    dest: /etc/openvpn/server.conf
    backup: yes
  notify:
    - restart openvpn

- name: enable ipv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: start openvpn server
  service:
    name: openvpn 
    enabled: yes
    state: started
