---
# pass newly configured keys to client host
- name: copy ovpn file to vpn client (from vpn_server to vpn_client)
  fetch:
    src: /etc/openvpn/easy-rsa/keys/{{ item }}.ovpn
    dest: openvpn_files/
    mode: 0644
    flat: yes
    # don't fail on missing, since manual setup still possible
  with_items: ssl_key_client_names

- name: copy key file to vpn client (from vpn_server to vpn_client)
  fetch:
    src: /etc/openvpn/easy-rsa/keys/{{ item }}.key
    dest: openvpn_files/
    mode: 0644
    flat: yes
    fail_on_missing: yes
  with_items: ssl_key_client_names

- name: copy cert file to vpn client (from vpn_server to vpn_client)
  fetch:
    src: /etc/openvpn/easy-rsa/keys/{{ item }}.crt
    dest: openvpn_files/
    mode: 0644
    flat: yes
    fail_on_missing: yes
  with_items: ssl_key_client_names

- name: copy ca file to vpn client (from vpn_server to vpn_client)
  fetch:
    src: /etc/openvpn/easy-rsa/keys/ca.crt
    dest: openvpn_files/
    mode: 0644
    flat: yes
    fail_on_missing: yes

