---
- name: create openvpn config
  template:
    src: server.conf.j2
    dest: /etc/openvpn/server.conf
    backup: yes
  with_items: digitalocean_vpn_client_names
  notify:
    - restart openvpn

- name: generate pem file
  command: >
    openssl dhparam
    -out /etc/openvpn/dh{{ ssl_key_bit_length }}.pem
    {{ ssl_key_bit_length }}
  args:
    creates: /etc/openvpn/dh{{ ssl_key_bit_length }}.pem

- name: enable ipv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
  changed_when: false

- name: start openvpn server
  # Using the service module works in Ubuntu 14.04
  # in Ansible v1.9.2 and later.
  service:
    name: openvpn
    state: started
    enabled: yes
    args: "{{ ssl_key_server_name }}"
  when: ansible_distribution == "Ubuntu"

- name: start openvpn server
  # Avoiding use of problematic `service` module pending
  # release of Ansible v2.0, see https://github.com/ansible/ansible-modules-core/issues/1298
  # Only noticed problem on Debian, because Debian has already migrated
  # to systemd (huzzah!).
  command: service openvpn start {{ ssl_key_server_name }}
  when: ansible_distribution == "Debian"
