---
# dopy is required for ansible digital_ocean module
- name: ensure dopy is installed (for digitalocean API)
easy_install: name=dopy

- name: create digitalocean droplet
  digital_ocean:
    command: droplet
    state: present
    name: vpn
    unique_name: true

    size_id: "{{ size_id }}"
    region_id: "{{ region_id }}"
    image_id: "{{ image_id }}"

    client_id: "{{ do_client_id }}"
    api_key: "{{ do_api_key }}"
    ssh_key_ids: "{{ do_ssh_key_id }}"

    wait_timeout: 200
  register: vpn_droplet
  tags:
    - digital_ocean
    - provision

- name: Add vpn droplet to inventory
  add_host:
    name: "{{ vpn_droplet.droplet.ip_address }}"
    ansible_ssh_user: root
    ansible_ssh_private_key_file: ~/.ssh/digital_ocean
    groups: do_droplets

- name: flush old IPs from SSH known_hosts
  shell: 'ssh-keygen -f "$HOME/.ssh/known_hosts" -R {{ vpn_droplet.droplet.ip_address }}'

- name: add new IP to SSH known_hosts
  shell: 'ssh-keyscan -H -T 10 {{ vpn_droplet.droplet.ip_address }} >> "$HOME/.ssh/known_hosts"'

- hosts: do_droplets
  roles:
    - { role: server, tags: 'vpn' }

