---
#- name: create networkmanager connection config file
#  template:
#    src: do-vpn-nm-conn.j2
#    dest: openvpn_files/do-vpn.nm
#    mode: "0600"
#  when: vpn_auto_configure

#- name: Create local .ovpn config files for clients.
#  template:
#    src: client.ovpn.j2
#    dest: openvpn_files/{{ item }}.ovpn
#    mode: "0600"
#  with_items: digitalocean_vpn_client_names

#- name: add openvpn config to networkmanager system-settings
#  copy:
#    src: openvpn_files/do-vpn.nm
#    dest: /etc/NetworkManager/system-connections/do-vpn
#    mode: "0600"
#    owner: root
#    group: root
#  when: vpn_auto_configure

- name: Remove preexisting connection for VPN.
  command: nmcli connection delete id "{{ digitalocean_vpn_nm_connection_name }}"
  # nmcli returns 11 if connection does not exist
  ignore_errors: yes
  tags:
    - jawn


- name: Create connection for VPN.
  command: >
    nmcli connection add
    con-name "DigitalOcean VPN"
    ifname tun0
    type vpn
    vpn-type openvpn
  tags:
    - jawn

