---
- include: fetch_keys.yml

#- include: manage_keys.yml

- include: create_nm_connection.yml
  # Haven't tested on 14.04 LTS, might work though.
  # The most important fact is the version of nmcli.
  # Will need to test much more extensively to support
  # other platforms.
  when: ansible_distribution == "Ubuntu" and
        ansible_distribution_major_version >= "15"

- name: Explain manual setup for VPN connection.
  debug:
    msg: >
      Your VPN server is ready. The configuration files have been
      fetched back to {{ digitalocean_vpn_client_cert_dir }}.
      Create a new VPN connection in in the networking settings
      for your OS. The IP address for the VPN server is
      {{ hostvars['vpn'].ansible_default_ipv4.address }}.
  when: ansible_distribution != "Ubuntu" or
        (ansible_distribution == "Ubuntu" and
        ansible_distribution_major_version < "15")
