---
- name: Create OpenVPN key directory.
  file:
    path: "{{ digitalocean_vpn_client_cert_dir }}"
    state: directory
    mode: "0750"

- name: Copy CA file to client.
  copy:
    src: openvpn_files/{{ item }}
    dest: "{{ digitalocean_vpn_client_cert_dir }}"
  with_items:
    - ca.crt

- name: Copy client certificates to localhost.
  copy:
    src: openvpn_files/{{ item }}.crt
    dest: "{{ digitalocean_vpn_client_cert_dir }}"
  with_items: digitalocean_vpn_client_names

- name: Copy client keys to localhost.
  copy:
    src: openvpn_files/{{ item }}.key
    dest: "{{ digitalocean_vpn_client_cert_dir }}"
  with_items: digitalocean_vpn_client_names

